/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SddsSpinner {
        "size": string;
        "type": string;
    }
    interface SliderTest {
    }
    interface SpinnerCircular {
        "size": string;
    }
    interface SpinnerCubic {
        "size": string;
    }
    interface SpinnerLinear {
        "size": string;
    }
}
declare global {
    interface HTMLSddsSpinnerElement extends Components.SddsSpinner, HTMLStencilElement {
    }
    var HTMLSddsSpinnerElement: {
        prototype: HTMLSddsSpinnerElement;
        new (): HTMLSddsSpinnerElement;
    };
    interface HTMLSliderTestElement extends Components.SliderTest, HTMLStencilElement {
    }
    var HTMLSliderTestElement: {
        prototype: HTMLSliderTestElement;
        new (): HTMLSliderTestElement;
    };
    interface HTMLSpinnerCircularElement extends Components.SpinnerCircular, HTMLStencilElement {
    }
    var HTMLSpinnerCircularElement: {
        prototype: HTMLSpinnerCircularElement;
        new (): HTMLSpinnerCircularElement;
    };
    interface HTMLSpinnerCubicElement extends Components.SpinnerCubic, HTMLStencilElement {
    }
    var HTMLSpinnerCubicElement: {
        prototype: HTMLSpinnerCubicElement;
        new (): HTMLSpinnerCubicElement;
    };
    interface HTMLSpinnerLinearElement extends Components.SpinnerLinear, HTMLStencilElement {
    }
    var HTMLSpinnerLinearElement: {
        prototype: HTMLSpinnerLinearElement;
        new (): HTMLSpinnerLinearElement;
    };
    interface HTMLElementTagNameMap {
        "sdds-spinner": HTMLSddsSpinnerElement;
        "slider-test": HTMLSliderTestElement;
        "spinner-circular": HTMLSpinnerCircularElement;
        "spinner-cubic": HTMLSpinnerCubicElement;
        "spinner-linear": HTMLSpinnerLinearElement;
    }
}
declare namespace LocalJSX {
    interface SddsSpinner {
        "size"?: string;
        "type"?: string;
    }
    interface SliderTest {
    }
    interface SpinnerCircular {
        "size"?: string;
    }
    interface SpinnerCubic {
        "size"?: string;
    }
    interface SpinnerLinear {
        "size"?: string;
    }
    interface IntrinsicElements {
        "sdds-spinner": SddsSpinner;
        "slider-test": SliderTest;
        "spinner-circular": SpinnerCircular;
        "spinner-cubic": SpinnerCubic;
        "spinner-linear": SpinnerLinear;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sdds-spinner": LocalJSX.SddsSpinner & JSXBase.HTMLAttributes<HTMLSddsSpinnerElement>;
            "slider-test": LocalJSX.SliderTest & JSXBase.HTMLAttributes<HTMLSliderTestElement>;
            "spinner-circular": LocalJSX.SpinnerCircular & JSXBase.HTMLAttributes<HTMLSpinnerCircularElement>;
            "spinner-cubic": LocalJSX.SpinnerCubic & JSXBase.HTMLAttributes<HTMLSpinnerCubicElement>;
            "spinner-linear": LocalJSX.SpinnerLinear & JSXBase.HTMLAttributes<HTMLSpinnerLinearElement>;
        }
    }
}
